### ISSUE TITLE
Rudde0 fork 

### ISSUE THREAD

**Issue by Keopsfenks** [SedatTR/AuctionMaster#3]
@rudde0 I'm using your fork. To keep it up to date.
I tried to build and use it, but it didn't work. 
![Screenshot_1](https://user-images.githubusercontent.com/51726168/181195026-2246299b-1ff4-4265-aea0-18e0baaac651.png)

Paper 1.18.2

`[09:00:53 ERROR]: Error occurred while enabling AuctionMaster v4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/objecthunter/exp4j/ExpressionBuilder
        at me.qKing12.AuctionMaster.FilesHandle.ConfigLoad.eval(ConfigLoad.java:158) ~[AuctionMaster-1.0.jar:?]
        at me.qKing12.AuctionMaster.FilesHandle.ConfigLoad.durationFeeCalculator(ConfigLoad.java:167) ~[AuctionMaster-1.0.jar:?]
        at me.qKing12.AuctionMaster.FilesHandle.ConfigLoad.<init>(ConfigLoad.java:547) ~[AuctionMaster-1.0.jar:?]
        at me.qKing12.AuctionMaster.AuctionMaster.onEnable(AuctionMaster.java:203) ~[AuctionMaster-1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.objecthunter.exp4j.ExpressionBuilder
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 15 more
[09:00:53 INFO]: [AuctionMaster] Disabling AuctionMaster v4.1`

**Comment by rudde0** [comment]
Just build the jar without ExpressionBuilder and hardcode the fee calculation in java file for now. I'll look into it in couple days.

**Comment by Keopsfenks** [comment]
> Just build the jar without ExpressionBuilder and hardcode the fee calculation in java file for now. I'll look into it in couple days.

ok i will try. Thank you.

**Comment by rudde0** [comment]
You can build now
